# Docs: https://aka.ms/yaml
name: $(Build.DefinitionName)_$(GitVersion_InformationalVersion)
pr:
- master

queue:
  name: Hosted VS2017

steps:
# - powershell: .\_build\bootstrap.ps1
#  displayName: 'Install pre-requisites'

#- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
#  displayName: 'Pester Test Runner'
#  inputs:
#    scriptFolder: '$(System.DefaultWorkingDirectory)\tests\*'
#    additionalModulePath: '$(Build.ArtifactStagingDirectory)'
#    resultsFile: '$(Common.TestResultsDirectory)\Test-$(Build.DefinitionName)_$(Build.BuildNumber).xml'

#- task: PublishTestResults@2
#  displayName: 'Publish Test Results'
#  condition: always()
#  inputs:
#    testRunner: NUnit
#    searchFolder: '$(Common.TestResultsDirectory)'

- powershell: Publish-Module -Name "devtools" -NuGetApiKey $(NugetAPIKey)
  displayName: 'Publish PowerShell Module'
